export const LOGIN = 'LOGIN';
export const FORGOT_PASSWORD_SUBMIT = 'FORGOT_PASSWORD_SUBMIT';
export const LOGOUT = 'LOGOUT';
export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS';
export const UPDATE_LOGIN_BTN_LOADING = 'UPDATE_LOGIN_BTN_LOADING';
export const UPDATE_APP_LOGGED = 'UPDATE_APP_LOGGED';
export const UPDATE_REDIRECT_TO_LOGIN = 'UPDATE_REDIRECT_TO_LOGIN';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CHECKING_LOGIN = 'CHECKING_LOGIN';
export const UPDATE_CHECKING_LOGIN = 'UPDATE_CHECKING_LOGIN';
export const UPDATE_SIGN_UP_BTN_LOADING = 'UPDATE_SIGN_UP_BTN_LOADING';
export const UPDATE_EMAIL_STATUS = 'UPDATE_EMAIL_STATUS';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const UPDATE_CHANGE_PASSWORD_MESSAGE_RESULT = 'UPDATE_CHANGE_PASSWORD_MESSAGE_RESULT'

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_MESSAGE_RESULT = 'UPDATE_PROFILE_MESSAGE_RESULT';

export const UPDATE_FORGOT_PASSWORD_BTN_LOADING = 'UPDATE_FORGOT_PASSWORD_BTN_LOADING';
export const UPDATE_FORGOT_PASSWORD_SEND_INSTRUCTION = 'UPDATE_FORGOT_PASSWORD_SEND_INSTRUCTION';
export const ON_FORGOT_PASSWORD_EMAIL_CHANGE = 'ON_FORGOT_PASSWORD_EMAIL_CHANGE';
export const CHECK_FORGOT_RESET_TOKEN = 'CHECK_FORGOT_RESET_TOKEN';
export const UPDATE_IS_CHECKING_RESET_PASSWORD = 'UPDATE_IS_CHECKING_RESET_PASSWORD';
export const UPDATE_VALID_TOKEN = 'UPDATE_VALID_TOKEN';
export const ON_RESET_PASSWORD_SUBMIT = 'ON_RESET_PASSWORD_SUBMIT';
export const UPDATE_BTN_SUBMIT_RESET = 'UPDATE_BTN_SUBMIT_RESET';
export const UPDATE_RESET_PASSWORD_MESSAGE_RESULT = 'UPDATE_RESET_PASSWORD_MESSAGE_RESULT';

export const RESET_NEW_APP_FORM = 'RESET_NEW_APP_FORM';
export const GET_LIST_APPS = 'GET_LIST_APPS';
export const NEW_APP_FIELDS_CHANGE = 'NEW_APP_FIELDS_CHANGE';
export const RECEIVED_LIST_APP_DATA = 'RECEIVED_LIST_APP_DATA';
export const UPDATE_GET_LIST_APP_LOADING = 'UPDATE_GET_LIST_APP_LOADING';
export const CREATE_NEW_APP = 'CREATE_NEW_APP';
export const UPDATE_APP = 'UPDATE_APP';
export const UPDATE_APP_BTN_LOADING = 'UPDATE_APP_BTN_LOADING';
export const CREATE_NEW_BTN_LOADING = 'CREATE_NEW_BTN_LOADING';
export const UPDATE_CREATE_NEW_APP_RESULT = 'UPDATE_CREATE_NEW_APP_RESULT';

export const RESET_EDIT_APP_FORM = 'RESET_EDIT_APP_FORM';
export const GET_DETAIL_APP_FOR_EDIT = 'GET_DETAIL_APP_FOR_EDIT';
export const GET_APPS_FOR_REPORT = 'GET_APPS_FOR_REPORT';
export const UPDATE_GET_APP_DETAIL_LOADING = 'UPDATE_GET_APP_DETAIL_LOADING';
export const RECEIVED_APP_DETAIL = 'RECEIVED_APP_DETAIL';

export const UPDATE_LOADING_APP_FOR_REPORT = 'UPDATE_LOADING_APP_FOR_REPORT';
export const RECEIVED_LIST_APP_REPORT = 'RECEIVED_LIST_APP_REPORT';
